config/routes.rb
Rails.application.routes.draw do

  resources :operations
  resources :histories, only: [:index, :show]
  resources :tasks
  get 'admin/new'
  
  resources :products
  resources :users
  resources :functions

  get 'login_admin' => 'sessions#new'
  post 'login_admin' => 'sessions#create'
  delete 'logout_admin' => 'sessions#destroy'
  root "users#index"

end

app/models/function.rb
class Function < ActiveRecord::Base
	has_and_belongs_to_many :products
	validates :factor, presence: true
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_action :set_function, only: [:show, :edit, :update, :destroy]

  # GET /functions
  # GET /functions.json
  def index
    @functions = Function.all
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
    @function = Function.find(params[:id])
    @products = @function.products
  end

  # GET /functions/new
  def new
    @function = Function.new
    @product = Product.all
  end

  # GET /functions/1/edit
  def edit
    @function = Function.find(params[:id])
    @product = Product.all
  end

  # POST /functions
  # POST /functions.json
  def create
    @function = Function.new(function_params)
    params[:product_id] ||= []
    @product = Product.find(params[:product_id])
    respond_to do |format|
      if @function.save
        @function.products << @product
        format.html { redirect_to @function, notice: 'Function was successfully created.' }
        format.json { render :show, status: :created, location: @function }
      else
        format.html { render :new }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functions/1
  # PATCH/PUT /functions/1.json
  def update
    params[:product_id] ||= []
    @product = Product.find(params[:product_id])
    respond_to do |format|
      @function.products.where(!@product).destroy_all
      if @function.update(function_params)
        @product.each do |p|
          if !@function.products.include?(p)
            @function.products << p
          end
        end
        format.html { redirect_to @function, notice: 'Function was successfully updated.' }
        format.json { render :show, status: :ok, location: @function }
      else
        format.html { render :edit }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @function.destroy
    respond_to do |format|
      format.html { redirect_to functions_url, notice: 'Function was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function
      @function = Function.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def function_params
      params.require(:function).permit(:name, :factor)
    end
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.erb
<%= form_for(@function) do |f| %>
  <% if @function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
      <% @function.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :factor %><br>
    <%= f.text_field :factor %>
  </div>

  <div class='field'>
    <% for prod in @product %>
      <%= check_box_tag "[product_id][]", prod.id, @function.product_ids.include?(prod.id), id: dom_id(prod) %>
    <%= label_tag dom_id(prod), prod.name %><br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/functions/edit.html.erb
<h1>Editing Function</h1>

<%= render 'form' %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

app/views/functions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Functions</h1>

<table class='function-table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @functions.each do |function| %>
      <tr>
        <td id='id'><%= function.id %></td>
        <td><%= function.name %></td>
        <td><%= link_to 'Show', function %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_function_path(function) %></td>
          <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
  <%= link_to 'New Function', new_function_path %>
<% end %>

app/views/functions/new.html.erb
<h1>New Function</h1>

<%= render 'form' %>

<%= link_to 'Back', functions_path %>

app/views/functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @function.name %>
</p>

<p>
  <strong>Factor:</strong>
  <%= @function.factor %>
</p>

<p>
  <strong>Products:</strong>
  <% @products.each do |p| %>
  <%= link_to p.name, p%>
  <% end %>
</p>

<% if logged_in? %>
	<%= link_to 'Edit', edit_function_path(@function) %> |
	<%= link_to 'Destroy', @function, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', functions_path %>