config/routes.rb
Rails.application.routes.draw do

  resources :operations
  resources :histories, only: [:index, :show]
  resources :tasks
  get 'admin/new'
  
  resources :products
  resources :users
  resources :functions

  get 'login_admin' => 'sessions#new'
  post 'login_admin' => 'sessions#create'
  delete 'logout_admin' => 'sessions#destroy'
  root "users#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :operations

	def set_task
		if self.id != nil
			@task = Task.find(self.id)
		else
			@task = Task.new
		end
	end

	def search(from, to)
 		self.set_task
		@time = @task.task_end
		if @time >= from.to_s && @time <= to.to_s
			true
		else
			false
		end
 	end

	def set_status
		self.set_task
		if DateTime.now > @task.task_end
			status = "Finished"
		elsif DateTime.now > @task.start && DateTime.now < @task.task_end
			status = "In progress"
		else
			status = "Not started yet"
		end
	end

	def total_duration
		self.set_task
		@operations = @task.operations
		total = 0
		@operations.each do |o|
			if o.duration != nil
				total = total+o.duration
			end
		end
		total
	end

	def total_rate
		self.set_task
		@operations = @task.operations
		total = 0
		@operations.each do |o|
			if o.duration && o.rate != nil
				total = total + o.rate*o.duration/60
			end
		end
		total	
	end

	def total_user_rate
		self.set_task
		@operations =@task.operations
		total = 0
		@operations.each do |o|
			total = total + o.total_users_rate
		end
		total
	end

	def total_task_rate
		self.set_task
		@operations = @task.operations
		cost = 0
		@operations.each do |o|
			cost = cost +o.total_users_rate
		end
		cost = cost + @task.total_rate
	end

	def total_users_average_rate
		self.set_task
		@operations = @task.operations
		total = 0
		@operations.each do |o|
			total = total + o.users_average_rate
		end
		if @operations.count != 0
			total = total/@operations.count
		else
			total
		end
	end

	def average_cost
		self.set_task
		if @task.operations.count != 0
			total = @task.total_rate/@task.operations.count
		else
			@task.total_rate
		end
	end 

	def average_total
		self.set_task
		if @task.operations.count != 0
			total = @task.total_task_rate/@task.operations.count
		else
			@task.total_task_rate
		end
	end

	def task_end
		finish = self.start + self.total_duration
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @cost = 0
    @users = 0
    @operations = 0 
    @tasks.each do |t|
      if t.total_task_rate && t.total_user_rate && t.total_rate
        @cost += t.total_task_rate
        @users += t.total_user_rate
        @operations += t.total_rate
      end
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @operations = @task.operations
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @operation = Operation.all
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @operation = Operation.all
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    params[:operation_id] ||= []
    @operation = Operation.find(params[:operation_id])
    respond_to do |format|
      if @task.save
        @task.operations << @operation
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    params[:operation_id] ||= []
    @operation = Operation.find(params[:operation_id])
    @taskop = @task.operations        
     respond_to do |format|
      @taskop.each do |t|
        if !@operation.include?(t)
          t.task_id = nil
          t.save
        end
      end
      @task.operations << @operation
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :start)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :starts_at %><br>
    <%= f.date_select :start %>
    <%= f.time_select :start, :ignore_date => true %>
  </div>

  <div class='field'>
    <% for op in @operation %>
      <%= check_box_tag "[operation_id][]", op.id, @task.operation_ids.include?(op.id), id: dom_id(op) %>
      <%= label_tag dom_id(op), op.name %><br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table class='user-table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Start</th>
      <th>Status</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td id='id'><%= task.id %></td>
        <td><%= task.name %></td>
        <td><%= task.start %></td>
        <td><%= task.set_status %></td>                
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<strong>Total Users's Cost: </strong><%= @users %> $<br>
<strong>Total Operations' Cost: </strong><%= @operations %> $<br>
<strong>Total Task's Cost: </strong><%= @cost %> $
<br><br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
	<strong>Operations:</strong>
	<% @operations.each do |o| %>
		<%= link_to o.name, o %>
	<% end %>
</p>

<p>
	<strong>Total Operations's duration: </strong>
	<%= @task.total_duration %> seconds
</p>

<p>
	<strong>Total Operation's cost: </strong>
	<%= @task.total_rate %> $
</p>

<p>
	<strong>Total Users's cost: </strong>
	<%= @task.total_user_rate %> $
</p>

<p>
	<strong>Total Task cost: </strong>
	<%= @task.total_task_rate %> $
</p>

<p>
	<strong>Operations' average cost: </strong>
	<%= @task.average_cost %> $
</p>

<p>
	<strong>Users' average rate:</strong>
	<%= @task.total_users_average_rate %> $/min
</p>

<p>
	<strong>Task average cost: </strong>
	<%= @task.average_total %> $
</p>

<p>
  <strong>Starts at:</strong>
  <%= @task.start %>
</p>

<p>
	<strong>Finishes at: </strong>
	<%= @task.task_end %>
</p>



<% if logged_in? %>
	<%= link_to 'Edit', edit_task_path(@task) %> |
	<%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', tasks_path %>