config/routes.rb
Rails.application.routes.draw do

  resources :operations
  resources :histories, only: [:index, :show]
  resources :tasks
  get 'admin/new'
  
  resources :products
  resources :users
  resources :functions

  get 'login_admin' => 'sessions#new'
  post 'login_admin' => 'sessions#create'
  delete 'logout_admin' => 'sessions#destroy'
  root "users#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
	before_save :total

	has_and_belongs_to_many :functions
	belongs_to :user
	validates :name, length: { maximum: 20},
					 presence: true	
	validates :price, presence: true

	def total
		if self.id != nil
			@product = Product.find(self.id)
		else
			@product = Product.new
		end
		total=1
		@function = @product.functions
		@function.each do |f|
			if f.factor != nil
				total = total*f.factor
			end
		end
		if @product.price != nil
			total = total*@product.price
		end
		total
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.find(params[:id])
    @functions = @product.functions
  end

  # GET /products/new
  def new
    @product = Product.new
    @function = Function.all
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @function = Function.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    params[:function_id] ||= []
    @function = Function.find(params[:function_id])
    respond_to do |format|
      if @product.save
        @product.functions << @function
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    params[:function_id] ||= []
    @function = Function.find(params[:function_id])
    respond_to do |format|
      @product.functions.where(!@function).destroy_all
      if @product.update(product_params)
          @function.each do |f|
            if !@product.functions.include?(f)
              @product.functions << f
            end
        end
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :user_id, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class='field'>
  <% for func in @function %>
    <%= check_box_tag "[function_id][]", func.id, @product.function_ids.include?(func.id), id: dom_id(func) %>
    <%= label_tag dom_id(func), func.name %><br>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class='user-table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>User</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td id='id'><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.user_id %></td>
        <td><%= link_to 'Show', product %></td>
        <% if logged_in? %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if logged_in? %>
<%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= @product.total %>
</p>

<p>
  <strong>Functions:</strong>
  <% @functions.each do |f| %>
  <%= link_to f.name, f%> 
  <% end %>
</p>


<% if logged_in? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', products_path %>