config/routes.rb
Rails.application.routes.draw do

  resources :operations
  resources :histories, only: [:index, :show]
  resources :tasks
  get 'admin/new'
  
  resources :products
  resources :users
  resources :functions

  get 'login_admin' => 'sessions#new'
  post 'login_admin' => 'sessions#create'
  delete 'logout_admin' => 'sessions#destroy'
  root "users#index"

end

app/models/operation.rb
class Operation < ActiveRecord::Base
	has_and_belongs_to_many :users
	belongs_to :task
	attr_accessor :total_duration, :count, :average

	def set_operation
		if self.id != nil
			@operation = Operation.find(self.id)
		else
			@operation = Operation.new
		end
	end

	def total_users_rate
		self.set_operation
		@users = @operation.users
		total = 0
		@users.each do |u|
			if u.rate != nil
				total = total + u.rate*@operation.duration/60
			end
		end
		if @users.count != 0
			total = total/@users.count
		else
			total
		end
	end

	def total_operation_rate
		self.set_operation
		total = @operation.rate*@operation.duration/60
	end

	def total_operation_cost
		self.set_operation
		total = @operation.total_operation_rate + @operation.total_users_rate
	end

	def users_average_rate
		self.set_operation
		@users =  @operation.users
		total = 0
		@users.each do |u|
			total = total + u.rate
		end
		if @users.count != 0
			total = total/@users.count
		else
			total
		end
	end

	def same_operation_duration
		self.total_duration

	end

	def same_operation_average
		self.set_operation
		average = self.same_operation_total_cost/self.count 
	end

	def same_operation_total_cost
		self.set_operation
		total = @operation.rate*self.total_duration/60
	end

	def same_user_total_cost
		self.set_operation
		@users = @operation.users
		@users.each do |u|
			total += u.rate*self.total_duration/60
		end
		total
	end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
    @operation = Operation.find(params[:id])
    @users = @operation.users
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
    @check = 1
    @operation = Operation.find(params[:id])
    @functions = Function.where({:name => @operation.name})
    @users = []
    @functions.each do |f|
      f.products.each do |p|
        if !@users.include?(User.find(p.user_id))
          @users.append(User.find(p.user_id))
        end    
      end
    end
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)
    params[:user_id] ||= []
    @users = User.find(params[:user_id])
    respond_to do |format|
      if @operation.save
        @operation.users << @users
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    params[:user_id] ||= []
    @user = User.find(params[:user_id])
    respond_to do |format|
      @operation.users.where(!@user).destroy_all
      if @operation.update(operation_params)
        @operation.users << @user
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:name, :rate, :duration, :task_id)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>

  <div class='field'>
    <%= f.label :rate %> <br>
    <%= f.text_field :rate %>
  </div>

  <div class='field'>
    <%= f.label :duration %> <br>
    <%= f.text_field :duration %>
  </div>

  <% if @check == 1 %>
  <div class='field'>
    <% for u in @users %>
      <%= check_box_tag "[user_id][]", u.id, @operation.user_ids.include?(u.id), id: dom_id(u) %>
      <%= label_tag dom_id(u), u.name %><br>
    <% end %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Operations</h1>

<table class='user-table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Rate</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.id %></td>
        <td><%= operation.name %></td>
        <td><%= operation.rate %></td>
        <td><%= operation.duration %></td>
        <td><%= link_to 'Show', operation %></td>
        <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @operation.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @operation.rate %>
</p>

<p>
	<strong>Duration:</strong>
	<%= @operation.duration %>
</p>

<p>
	<strong>Users:</strong>
	<% @users.each do |u| %>
		<%= link_to u.name, u %>
	<%end %>
</p>

<p>
	<strong>Users' average rate:</strong>
	<%= @operation.users_average_rate %>
</p>

<p>
	<strong>Operation cost:</strong>
	<%= @operation.total_operation_rate %> $
</p>

<p>
	<strong>Total Users' cost:</strong>
	<%= @operation.total_users_rate %> $
</p>

<p>
	<strong>Total Operation cost:</strong>
	<%= @operation.total_operation_cost %> $
</p>

<% if logged_in? %>
	<%= link_to 'Edit', edit_operation_path(@operation) %> |
	<%= link_to 'Destroy', @operation, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', operations_path %>